# Generated by Django 3.2 on 2021-07-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('open_count', models.IntegerField(blank=True, default=0, null=True)),
                ('first_open_datetime', models.DateTimeField(blank=True, null=True)),
                ('latest_open_datetime', models.DateTimeField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_tracking_data',
            },
        ),
    ]
